topics:
  - "Research Agreement Types and Use Cases"
  - "IEP Contracting Hub Usage"
  - "Eligibility for Grant Application (PI/Co-PI)"
  - "Templates and Legal Documents"
  - "Pre-Award Grant Application Process"
  - "Indirect Research Costs (IRC) and Budgeting"
  - "Material and Data Transfer Agreements"
  - "Post-Award Grant Administration"
  - "WBS Account Creation and Activation"
  - "Inter-NUS Collaborations"
  - "Grant Progress Reporting"
  - "Handling Extended Leave or Resignation"
  - "Consultancy vs Contract Research"
  - "IRB and Ethics Approval Requirements"
  - "Procurement and Legal Support Contacts"