name: odprt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pillow=10.4.0
  - pytorch=2.2.0
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - asgiref==3.8.1
      - attrs==24.2.0
      - backoff==2.2.1
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - build==1.2.2.post1
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.17
      - click==8.1.7
      - colorama==0.4.6
      - colorclass==2.2.2
      - coloredlogs==15.0.1
      - compressed_rtf==1.0.6
      - cryptography==43.0.3
      - dataclasses-json==0.6.7
      - Deprecated==1.2.14
      - distlib==0.3.9
      - distro==1.9.0
      - durationpy==0.9
      - extract-msg==0.52.0
      - fastapi==0.115.4
      - fastembed==0.4.1
      - filelock==3.16.1
      - flask==3.0.3
      - flask-cors==5.0.0
      - flatbuffers==24.3.25
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - google-api-core==2.22.0
      - google-api-python-client==2.151.0
      - google-auth==2.35.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - googleapis-common-protos==1.65.0
      - greenlet==3.1.1
      - grpcio==1.67.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.2
      - humanfriendly==10.0
      - identify==2.6.1
      - idna==3.10
      - importlib_metadata==8.4.0
      - importlib_resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kubernetes==31.0.0
      - langchain==0.2.16
      - langchain-community==0.2.17
      - langchain-core==0.2.43
      - langchain-mistralai==0.1.13
      - langchain-openai==0.1.15
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.139
      - lark==1.1.9
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.1
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - msoffcrypto-tool==5.4.2
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nemoguardrails==0.10
      - FlagEmbedding
      - pymilvus
      - milvus_model
      - selenium==4.28.1
      - beautifulsoup4==4.12.3
      - langchain-groq==0.1.2
      - langcodes==3.3.0
      - ragas==0.1.7
      - llama-cloud==0.1.11
      - llama-cloud-services==0.6.0
      - llama-index==0.12.16
      - llama-index-agent-openai==0.4.3
      - llama-index-cli==0.4.0
      - llama-index-core==0.12.16.post1
      - llama-index-embeddings-openai==0.3.1
      - llama-index-indices-managed-llama-cloud==0.6.4
      - llama-index-llms-openai==0.3.18
      - llama-index-multi-modal-llms-openai==0.4.3
      - llama-index-program-openai==0.3.1
      - llama-index-question-gen-openai==0.3.0
      - llama-index-readers-file==0.4.4
      - llama-index-readers-llama-parse==0.4.0
      - llama-parse==0.6.0
