name: odprt
channels:
  - conda-forge
dependencies:
- adwaita-icon-theme
- aiohappyeyeballs
- aiohttp
- aiosignal
- annotated-types
- aom
- appnope
- asttokens
- async-timeout
- atk-1.0
- attrs
- aws-c-auth
- aws-c-cal
- aws-c-common
- aws-c-compression
- aws-c-event-stream
- aws-c-http
- aws-c-io
- aws-c-mqtt
- aws-c-s3
- aws-c-sdkutils
- aws-checksums
- aws-crt-cpp
- aws-sdk-cpp
- azure-core-cpp
- azure-identity-cpp
- azure-storage-blobs-cpp
- azure-storage-common-cpp
- azure-storage-files-datalake-cpp
- backcall
- backports
- backports.functools_lru_cache
- blas
- blas-devel
- bottleneck
- brotli-python
- bzip2
- c-ares
- ca-certificates
- cairo
- certifi
- cffi
- charset-normalizer
- click
- colorama
- comm
- cpython
- dataclasses-json
- datasets
- dav1d
- dbus
- debugpy
- decorator
- deprecation
- dill
- distro
- einops
- epoxy
- exceptiongroup
- executing
- expat
- ffmpeg
- fftw
- font-ttf-dejavu-sans-mono
- font-ttf-inconsolata
- font-ttf-source-code-pro
- font-ttf-ubuntu
- fontconfig
- fonts-conda-ecosystem
- fonts-conda-forge
- fpdf
- freetype
- fribidi
- frozenlist
- fsspec
- ftfy
- future
- gdk-pixbuf
- gflags
- ghostscript
- giflib
- glib
- glib-tools
- glog
- gmp
- gmpy2
- gotrue
- graphite2
- graphviz
- greenlet
- grpcio
- grpcio-tools
- gtk3
- gts
- h11
- h2
- harfbuzz
- hdf5
- hicolor-icon-theme
- hpack
- httpx
- httpx-sse
- hyperframe
- icu
- idna
- imagemagick
- imath
- importlib-metadata
- importlib_metadata
- ipykernel
- ipython
- jasper
- jbig
- jedi
- jinja2
- jiter
- joblib
- jsonpatch
- jsonpointer
- jupyter_client
- jupyter_core
- krb5
- lame
- langchain-experimental
- lcms2
- lerc
- libabseil
- libaec
- libarrow
- libarrow-acero
- libarrow-dataset
- libarrow-substrait
- libasprintf
- libass
- libavif16
- libblas
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcblas
- libcrc32c
- libcurl
- libcxx
- libde265
- libdeflate
- libedit
- libev
- libevent
- libexpat
- libffi
- libgd
- libgettextpo
- libgfortran
- libgfortran5
- libglib
- libgoogle-cloud
- libgoogle-cloud-storage
- libgrpc
- libheif
- libhwloc
- libiconv
- libintl
- libintl-devel
- libjpeg-turbo
- liblapack
- liblapacke
- liblzma
- liblzma-devel
- libnghttp2
- libopenblas
- libopencv
- libopentelemetry-cpp
- libopentelemetry-cpp-headers
- libopenvino
- libopenvino-arm-cpu-plugin
- libopenvino-auto-batch-plugin
- libopenvino-auto-plugin
- libopenvino-hetero-plugin
- libopenvino-ir-frontend
- libopenvino-onnx-frontend
- libopenvino-paddle-frontend
- libopenvino-pytorch-frontend
- libopenvino-tensorflow-frontend
- libopenvino-tensorflow-lite-frontend
- libopus
- libparquet
- libpng
- libprotobuf
- libre2-11
- librsvg
- libsodium
- libsqlite
- libssh2
- libthrift
- libtiff
- libtmglib
- libusb
- libutf8proc
- libvpx
- libwebp
- libwebp-base
- libxcb
- libxml2
- libxslt
- libzlib
- llvm-openmp
- lxml
- lz4-c
- markupsafe
- matplotlib-inline
- mpc
- mpfr
- mpmath
- multidict
- multiprocess
- mypy_extensions
- ncurses
- nest-asyncio
- networkx
- ninja
- ninja-base
- nlohmann_json
- nspr
- nss
- numexpr
- numpy
- openai
- opencv
- openexr
- openh264
- openjpeg
- openssl
- orc
- orjson
- packaging
- pandas
- pango
- parso
- pcre2
- pdf2image
- pdfminer.six
- pdfplumber
- peft
- perl
- pexpect
- pickleshare
- pip
- pixman
- pkg-config
- platformdirs
- poppler
- poppler-data
- postgrest
- prometheus-cpp
- prompt-toolkit
- prompt_toolkit
- propcache
- protobuf
- psutil
- pthread-stubs
- ptyprocess
- pugixml
- pure_eval
- py-opencv
- pyarrow
- pyarrow-core
- pycparser
- pydantic
- pydantic-core
- pydantic-settings
- pygments
- pysocks
- pytesseract
- python
- python-dateutil
- python-docx
- python-dotenv
- python-multipart
- python-tzdata
- python-xxhash
- python_abi
- pytorch
- pytz
- pyyaml
- pyzmq
- rav1e
- re2
- readline
- realtime
- regex
- requests
- requests-toolbelt
- safetensors
- scipy
- sdl2
- sdl3
- setuptools
- six
- snappy
- sniffio
- sqlalchemy
- sqlite
- stack_data
- storage3
- strenum
- supabase
- supafunc
- svt-av1
- tbb
- threadpoolctl
- timm
- tk
- torchaudio
- torchvision
- tornado
- tqdm
- traitlets
- transformers
- typing-extensions
- typing_extensions
- typing_inspect
- tzdata
- ujson
- urllib3
- wand
- wcwidth
- websockets
- wheel
- x264
- x265
- xorg-libice
- xorg-libsm
- xorg-libx11
- xorg-libxau
- xorg-libxdmcp
- xorg-libxext
- xorg-libxrender
- xorg-libxt
- xxhash
- xz
- xz-gpl-tools
- xz-tools
- yaml
- yarl
- zeromq
- zipp
- zlib
- zstandard
- zstd
- pip:
  - accelerate==1.3.0
  - annoy==1.17.3
  - anyio==4.6.2.post1
  - appscript==1.3.0
  - asgiref==3.8.1
  - backoff==2.2.1
  - bcrypt==4.2.0
  - beautifulsoup4==4.12.3
  - blinker==1.8.2
  - build==1.2.2.post1
  - cachetools==5.5.0
  - cbor==1.0.0
  - cfgv==3.4.0
  - chroma-hnswlib==0.7.6
  - chromadb==0.5.17
  - colorclass==2.2.2
  - coloredlogs==15.0.1
  - compressed-rtf==1.0.6
  - cryptography==43.0.3
  - deprecated==1.2.14
  - distlib==0.3.9
  - docx2pdf==0.1.8
  - durationpy==0.9
  - easygui==0.98.3
  - ebcdic==1.1.1
  - extract-msg==0.52.0
  - fastapi==0.115.4
  - fastembed==0.4.1
  - filelock==3.16.1
  - flagembedding==1.3.4
  - flask==3.0.3
  - flask-cors==5.0.0
  - flatbuffers==24.3.25
  - google-api-core==2.22.0
  - google-api-python-client==2.151.0
  - google-auth==2.35.0
  - google-auth-httplib2==0.2.0
  - google-auth-oauthlib==1.2.1
  - googleapis-common-protos==1.65.0
  - httpcore==1.0.6
  - httplib2==0.22.0
  - httptools==0.6.4
  - huggingface-hub==0.28.1
  - humanfriendly==10.0
  - identify==2.6.1
  - ijson==3.3.0
  - importlib-resources==6.4.5
  - inscriptis==2.5.3
  - ir-datasets==0.5.9
  - itsdangerous==2.2.0
  - kubernetes==31.0.0
  - langchain==0.2.16
  - langchain-community==0.2.17
  - langchain-core==0.2.43
  - langchain-mistralai==0.1.13
  - langchain-openai==0.1.15
  - langchain-text-splitters==0.2.4
  - langsmith==0.1.139
  - lark==1.1.9
  - loguru==0.7.2
  - lz4==4.4.3
  - markdown-it-py==3.0.0
  - marshmallow==3.23.1
  - mdurl==0.1.2
  - milvus-lite==2.4.11
  - milvus-model==0.2.12
  - mmh3==4.1.0
  - monotonic==1.6
  - msoffcrypto-tool==5.4.2
  - nemoguardrails==0.10.0
  - oauthlib==3.2.2
  - olefile==0.47
  - oletools==0.60.2
  - onnx==1.17.0
  - onnxruntime==1.19.2
  - opentelemetry-api==1.30.0
  - opentelemetry-exporter-otlp-proto-common==1.30.0
  - opentelemetry-exporter-otlp-proto-grpc==1.30.0
  - opentelemetry-instrumentation==0.51b0
  - opentelemetry-instrumentation-asgi==0.51b0
  - opentelemetry-instrumentation-fastapi==0.51b0
  - opentelemetry-proto==1.30.0
  - opentelemetry-sdk==1.30.0
  - opentelemetry-semantic-conventions==0.51b0
  - opentelemetry-util-http==0.51b0
  - overrides==7.7.0
  - pcodedmp==1.2.6
  - pillow==10.4.0
  - posthog==3.11.0
  - proto-plus==1.26.0
  - py-rust-stemmers==0.1.3
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.1
  - pymilvus==2.5.4
  - pyparsing==3.2.1
  - pypika==0.48.9
  - pyproject-hooks==1.2.0
  - red-black-tree-mod==1.20
  - requests-oauthlib==2.0.0
  - rich==13.9.4
  - rsa==4.9
  - rtfde==0.1.2
  - scikit-learn==1.6.1
  - sentence-transformers==3.4.1
  - sentencepiece==0.2.0
  - shellingham==1.5.4
  - simpleeval==1.0.3
  - soupsieve==2.6
  - starlette==0.41.3
  - sympy==1.13.1
  - tenacity==8.5.0
  - tiktoken==0.8.0
  - tokenizers==0.20.3
  - tomli==2.2.1
  - trec-car-tools==2.6
  - typer==0.15.1
  - tzlocal==5.2
  - unlzw3==0.2.3
  - uritemplate==4.1.1
  - uvicorn==0.34.0
  - uvloop==0.21.0
  - warc3-wet==0.2.5
  - warc3-wet-clueweb09==0.2.5
  - watchdog==6.0.0
  - watchfiles==1.0.4
  - websocket-client==1.8.0
  - werkzeug==3.1.3
  - wrapt==1.17.2
  - zlib-state==0.1.9
